<?php
/**
 * ITEP_Incomm extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE_FH.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       ITEP
 * @package        ITEP_Incomm
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php
/**
 * @see ITEP_Incomm_Block_Hello
 */
?>
<h2><?php echo $this->getBlockHeading() ?></h2>
<p><?php echo $this->getContent() ?></p>